if (hdr.genhdr_uid1.isValid()){
	#define OUTPUT_HEADER_SIZE 1
	bit<64> tmp;
	bit<32> index;
	index = 0;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 1;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 2;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 3;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 4;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 5;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 6;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 7;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 8;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	index = 9;
	msgbox.read(tmp,index);
	tmp = tmp + 1;
	msgbox.write(index,tmp);
	tmp = tmp + 1;
	tmp = tmp + 2;
	tmp = tmp + 3;
	tmp = tmp + 4;
	tmp = tmp + 5;
	tmp = tmp + 6;
	tmp = tmp + 7;
	tmp = tmp + 8;
	tmp = tmp + 9;
	tmp = tmp + 10;
	#undef OUTPUT_HEADER_SIZE
}
